### PR TITLE
Add selective log message

### PR DESCRIPTION
**Pull request by DK-sr**
Add cmake option for giving choice whether turning on output log message or not.

### CODE REVIEW

**Comment by KangJH** [comment]
Is there any reason to make CMake option for on/off logging?
Because we already has "logging.enable_terminal_logging" in app_settings.toml.

**Comment by DK-sr** [comment]
> Is there any reason to make CMake option for on/off logging?
> Because we already has "logging.enable_terminal_logging" in app_settings.toml.

Then is that means user should change app_setting.toml manually if they want to remove the message? I wonder we mention this in our manual. I think we can rather just disable this as default and then if the user needs those basic debug messages, they can enable on this cmakelist. The most worrying case is user need to restart the project once they check the value of the app_settings.toml(Please double-check this I am not sure the exact sequence of applying app_settings).

**Comment by KangJH** [comment]
> Then is that means user should change app_setting.toml manually if they want to remove the message? 

Yes, it is.
> I wonder we mention this in our manual. 

No

> I think we can rather just disable this as default and then if the user needs those basic debug messages, they can enable on this cmakelist.

How about to change default level of logging instead of turn off all debug message?
Then, we will get error message at least.

> The most worrying case is user need to restart the project once they check the value of the app_settings.toml(Please double-check this I am not sure the exact sequence of applying app_settings).

Yes, user should re-run master node to apply the changes. We don't open any GUI menu for logging.

**Comment by DK-sr** [comment]
@KangJH Sorry but I don't get your point clearly. The reason for making his pr is removing the debug log of SENSR SDK which is similar to "New OutputMessage" and remains a selective option for debugging purposes. I think you misunderstood our sensr logging system. Or do we also have logging level about SENSR SDK printed messages?

**Comment by KangJH** [comment]
> @KangJH Sorry but I couldn't get your point clearly. The reason for making this pr is removing the debug log of SENSR SDK which is similar to "New OutputMessage" and remains a selective option for debugging purposes. I think you misunderstood our sensr logging system. Or do we also have logging level about SENSR SDK printed messages?

Oh, sorry!!! my mistake.. I thought this was SENSR... Will approve this.

**Review by KangJH — APPROVED** [review]

**Pull request merged**
